version: '3.1'

services:
  api:
    build: .
    container_name: node-essential
    ports:
      - 8080:8080
    env_file:
      - .env.production
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
