swagger: "2.0"
info:
  description: "This is a sample swagger."
  version: "1.0.0"
  title: "Swagger node essential"
  contact:
    email: "jdrodriguez623@outlook.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api/v1"
tags:
  - name: "hello"
    description: "Simple hello"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
schemes:
  - "http"
paths:
  /hello:
    get:
      tags:
        - "hello"
      summary: "Hello message"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hello"
  /createConsent:
    post:
      tags:
        - "Create a new Consent"
      summary: "Create a new consent request"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GeneratedCode"
  /getConsents:
    get:
      tags:
        - "Generate Code"
      summary: "Generate 6 digits code unique for the user."
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GeneratedCode"
definitions:
  Hello:
    type: "object"
    properties:
      title:
        type: "string"
      message:
        type: "string"
  GeneratedCode:
    type: "object"
    properties:
      title:
        type: "string"
      code:
        type: "string"
